"""add new columns ('user_id', 'name', and 'type') to the 'Document' table

Revision ID: 10d7305c4979
Revises: 26c1de07a3e8
Create Date: 2024-10-30 19:52:45.885783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d7305c4979'
down_revision: Union[str, None] = '26c1de07a3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('_document', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('_document', sa.Column('name', sa.String(), nullable=False))
    op.add_column('_document', sa.Column('type', sa.String(), nullable=False))
    op.drop_index('ix_document_path', table_name='_document')
    op.create_index('ix_document_user_id', '_document', ['user_id'], unique=False)
    op.create_foreign_key(None, '_document', '_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, '_document', type_='foreignkey')
    op.drop_index('ix_document_user_id', table_name='_document')
    op.create_index('ix_document_path', '_document', ['path'], unique=False)
    op.drop_column('_document', 'type')
    op.drop_column('_document', 'name')
    op.drop_column('_document', 'user_id')
    # ### end Alembic commands ###
