"""define 'User' and 'Session' tables

Revision ID: 26c1de07a3e8
Revises: 5243d9f00080
Create Date: 2024-10-30 19:23:59.541991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26c1de07a3e8'
down_revision: Union[str, None] = '5243d9f00080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sentence_document_id_node_id', table_name='sentence')
    op.drop_table('sentence')
    op.drop_index('ix_node_document_id_parent_id', table_name='node')
    op.drop_table('node')
    op.drop_index('ix_document_path', table_name='document')
    op.drop_table('document')
    op.create_table('_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_index('ix_document_path', '_document', ['path'], unique=False)
    op.create_table('_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_userId', '_session', ['userId'], unique=False)
    op.create_table('_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('isPermanent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_user_username', '_user', ['username'], unique=False)
    op.create_table('_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('topic_and_content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['_document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id', 'document_id'], ['_node.id', '_node.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'document_id')
    )
    op.create_index('ix_node_document_id_parent_id', '_node', ['document_id', 'parent_id'], unique=False)
    op.create_table('_sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embeddings', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['_document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id', 'document_id'], ['_node.id', '_node.document_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'document_id')
    )
    op.create_index('ix_sentence_document_id_node_id', '_sentence', ['document_id', 'node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('document_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='document_pkey'),
    sa.UniqueConstraint('path', name='document_path_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_document_path', 'document', ['path'], unique=False)
    op.create_table('sentence',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('embeddings', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name='sentence_document_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id', 'document_id'], ['node.id', 'node.document_id'], name='sentence_node_id_document_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'document_id', name='sentence_pkey')
    )
    op.create_index('ix_sentence_document_id_node_id', 'sentence', ['document_id', 'node_id'], unique=False)
    op.create_table('node',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic_and_content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name='node_document_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id', 'document_id'], ['node.id', 'node.document_id'], name='node_parent_id_document_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'document_id', name='node_pkey')
    )
    op.create_index('ix_node_document_id_parent_id', 'node', ['document_id', 'parent_id'], unique=False)
    op.drop_index('ix_sentence_document_id_node_id', table_name='_sentence')
    op.drop_table('_sentence')
    op.drop_index('ix_node_document_id_parent_id', table_name='_node')
    op.drop_table('_node')
    op.drop_index('ix_user_username', table_name='_user')
    op.drop_table('_user')
    op.drop_index('ix_session_userId', table_name='_session')
    op.drop_table('_session')
    op.drop_index('ix_document_path', table_name='_document')
    op.drop_table('_document')
    # ### end Alembic commands ###
